# Generated by Django 4.1.6 on 2023-02-16 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Denials",
            fields=[
                ("denial_id", models.AutoField(primary_key=True, serialize=False)),
                ("hashed_email", models.CharField(max_length=300)),
                ("denial_text", models.CharField(max_length=30000000)),
                ("submissions", models.DateField()),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FollowUpType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=300)),
                ("text", models.CharField(max_length=30000)),
                ("duration", models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name="PlanType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="FollowUpSched",
            fields=[
                ("follow_up_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=300)),
                ("follow_up_date", models.DateField()),
                ("initial", models.DateField(auto_now_add=True)),
                (
                    "follow_up_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.followuptype",
                    ),
                ),
            ],
        ),
    ]
