# Generated by Django 4.2.3 on 2023-08-30 22:20

import django.db.models.deletion
from django.db import migrations, models

import regex_field.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Denial",
            fields=[
                ("denial_id", models.AutoField(primary_key=True, serialize=False)),
                ("hashed_email", models.CharField(max_length=300)),
                ("denial_text", models.TextField(max_length=30000000)),
                ("date", models.DateField(auto_now_add=True)),
                ("urgent", models.BooleanField(default=False)),
                ("pre_service", models.BooleanField(default=False)),
                ("denial_date", models.DateField(null=True)),
                ("insurance_company", models.CharField(max_length=300, null=True)),
                ("claim_id", models.CharField(max_length=300, null=True)),
                ("procedure", models.CharField(max_length=300, null=True)),
                ("diagnosis", models.CharField(max_length=300, null=True)),
                ("appeal_text", models.TextField(max_length=3000000000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DenialTypes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300)),
                ("regex", regex_field.fields.RegexField(max_length=400)),
                ("negative_regex", regex_field.fields.RegexField(max_length=400)),
                ("appeal_text", models.TextField(blank=True, max_length=3000)),
                ("form", models.CharField(max_length=300, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="fighthealthinsurance.denialtypes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300)),
                ("regex", regex_field.fields.RegexField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="FollowUpType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="", max_length=300)),
                ("subject", models.CharField(max_length=300)),
                ("text", models.TextField(max_length=30000)),
                ("duration", models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name="PlanType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300)),
                ("alt_name", models.CharField(max_length=300)),
                ("regex", regex_field.fields.RegexField(max_length=400)),
                ("negative_regex", regex_field.fields.RegexField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="Procedures",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300)),
                ("regex", regex_field.fields.RegexField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="Regulator",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300)),
                ("website", models.CharField(max_length=300)),
                ("alt_name", models.CharField(max_length=300)),
                ("regex", regex_field.fields.RegexField(max_length=400)),
                ("negative_regex", regex_field.fields.RegexField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="PlanTypesRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "denial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.denial",
                    ),
                ),
                (
                    "plan_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.plantype",
                    ),
                ),
                (
                    "src",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fighthealthinsurance.datasource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FollowUpSched",
            fields=[
                ("follow_up_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=300)),
                ("follow_up_date", models.DateField()),
                ("initial", models.DateField(auto_now_add=True)),
                (
                    "denial_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.denial",
                    ),
                ),
                (
                    "follow_up_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.followuptype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DenialTypesRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "denial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.denial",
                    ),
                ),
                (
                    "denial_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.denialtypes",
                    ),
                ),
                (
                    "src",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fighthealthinsurance.datasource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="denial",
            name="denial_type",
            field=models.ManyToManyField(
                through="fighthealthinsurance.DenialTypesRelation",
                to="fighthealthinsurance.denialtypes",
            ),
        ),
        migrations.AddField(
            model_name="denial",
            name="plan_type",
            field=models.ManyToManyField(
                through="fighthealthinsurance.PlanTypesRelation",
                to="fighthealthinsurance.plantype",
            ),
        ),
        migrations.AddField(
            model_name="denial",
            name="regulator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fighthealthinsurance.regulator",
            ),
        ),
    ]
