# Generated by Django 4.1.7 on 2023-09-01 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposedAppeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appeal_text", models.TextField(max_length=3000000000, null=True)),
                (
                    "for_denial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.denial",
                    ),
                ),
            ],
        ),
    ]
