# Generated by Django 4.1.6 on 2023-02-23 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="denial",
            name="submissions",
        ),
    ]
