# Generated by Django 4.2.3 on 2023-09-26 00:50

from django.db import migrations, models
import regex_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0002_proposedappeal"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppealTemplates",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300)),
                ("regex", regex_field.fields.RegexField(max_length=400)),
                ("negative_regex", regex_field.fields.RegexField(max_length=400)),
                ("appeal_text", models.TextField(blank=True, max_length=3000)),
            ],
        ),
    ]
