# Generated by Django 5.0.4 on 2024-07-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0003_appealtemplates"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposedappeal",
            name="chosen",
            field=models.BooleanField(default=False),
        ),
    ]
