# Generated by Django 4.1.6 on 2023-02-25 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0003_remove_denial_regulator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="denial_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="pre_service",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="denial",
            name="urgent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="followuptype",
            name="name",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.CreateModel(
            name="PlanTypesRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "denial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.denial",
                    ),
                ),
                (
                    "plan_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.plantype",
                    ),
                ),
                (
                    "src",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fighthealthinsurance.datasource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="denial",
            name="plan_type",
            field=models.ManyToManyField(
                through="fighthealthinsurance.PlanTypesRelation",
                to="fighthealthinsurance.plantype",
            ),
        ),
    ]
