# Generated by Django 5.0.4 on 2024-07-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0004_proposedappeal_chosen"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposedappeal",
            name="editted",
            field=models.BooleanField(default=False),
        ),
    ]
