# Generated by Django 4.1.6 on 2023-03-06 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0004_denial_denial_date_denial_pre_service_denial_urgent_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="regulator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fighthealthinsurance.regulator",
            ),
        ),
    ]
