# Generated by Django 5.0.4 on 2024-07-31 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0005_proposedappeal_editted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposedappeal",
            name="for_denial",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fighthealthinsurance.denial",
            ),
        ),
    ]
