# Generated by Django 4.1.6 on 2023-03-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0006_denialtypes_appeal_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="claim_id",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="insurance_company",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
