# Generated by Django 5.0.4 on 2024-08-01 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0006_alter_proposedappeal_for_denial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposedappeal",
            name="for_denial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fighthealthinsurance.denial",
            ),
        ),
    ]
