# Generated by Django 4.1.6 on 2023-03-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0007_denial_claim_id_denial_insurance_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="denialtypes",
            name="form",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
