# Generated by Django 5.0.4 on 2024-08-19 19:13

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0007_alter_proposedappeal_for_denial"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="created",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(), null=True
            ),
        ),
        migrations.AddField(
            model_name="denial",
            name="raw_email",
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="use_external",
            field=models.BooleanField(default=False),
        ),
    ]
