# Generated by Django 5.0.8 on 2024-08-29 01:04

import regex_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0008_denial_created_denial_raw_email_denial_use_external",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="appealtemplates",
            name="diagnosis_regex",
            field=regex_field.fields.RegexField(blank=True, max_length=400),
        ),
    ]
