# Generated by Django 5.0.8 on 2024-09-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0009_appealtemplates_diagnosis_regex"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="medical_context",
            field=models.TextField(max_length=300000, null=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="qa_context",
            field=models.TextField(max_length=300000, null=True),
        ),
    ]
