# Generated by Django 5.0.8 on 2024-09-08 04:29

import regex_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0010_denial_medical_context_denial_qa_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanSource",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300)),
                ("regex", regex_field.fields.RegexField(max_length=400)),
                ("negative_regex", regex_field.fields.RegexField(max_length=400)),
            ],
        ),
    ]
