# Generated by Django 4.1.7 on 2023-07-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0010_rename_treatment_denial_diagnosis"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="appeal_text",
            field=models.CharField(max_length=3000000000, null=True),
        ),
    ]
