# Generated by Django 5.0.8 on 2024-09-08 05:27

import django.db.models.deletion
from django.db import migrations, models

import regex_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0010_denial_medical_context_denial_qa_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanSource",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300)),
                ("regex", regex_field.fields.RegexField(max_length=400)),
                ("negative_regex", regex_field.fields.RegexField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="PlanSourceRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "denial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.denial",
                    ),
                ),
                (
                    "plan_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.plansource",
                    ),
                ),
                (
                    "src",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fighthealthinsurance.datasource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="denial",
            name="plan_source",
            field=models.ManyToManyField(
                through="fighthealthinsurance.PlanSourceRelation",
                to="fighthealthinsurance.plansource",
            ),
        ),
    ]
