# Generated by Django 5.0.8 on 2024-09-08 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0011_plansource"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanSourceRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "denial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.denial",
                    ),
                ),
                (
                    "plan_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.plansource",
                    ),
                ),
                (
                    "src",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fighthealthinsurance.datasource",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="denial",
            name="plan_type",
            field=models.ManyToManyField(
                through="fighthealthinsurance.PlanSourceRelation",
                to="fighthealthinsurance.plansource",
            ),
        ),
    ]
