# Generated by Django 5.1.1 on 2024-09-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0012_denial_semi_sekret"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="denial_type_text",
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="plan_id",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="state",
            field=models.CharField(max_length=4, null=True),
        ),
    ]
