# Generated by Django 5.0.8 on 2024-09-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0012_denial_semi_sekret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denial",
            name="appeal_text",
            field=models.TextField(max_length=30000000000, null=True),
        ),
        migrations.AlterField(
            model_name="denial",
            name="denial_text",
            field=models.TextField(max_length=300000000),
        ),
    ]
