# Generated by Django 5.1.1 on 2024-09-24 02:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0015_rename_medical_context_denial_health_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="plan_documents",
            field=models.FileField(
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="external_data"
                ),
                upload_to="",
            ),
        ),
    ]
