# Generated by Django 5.0.8 on 2024-09-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0020_remove_interestedprofessional_most_common_denial_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="denial",
            name="appeal_text",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="denial",
            name="denial_text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="denial",
            name="health_history",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="denial",
            name="qa_context",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="interestedprofessional",
            name="comments",
            field=models.TextField(default=""),
        ),
    ]
