# Generated by Django 5.0.8 on 2024-09-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0021_alter_denial_appeal_text_alter_denial_denial_text_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="interestedprofessional",
            name="job_title_or_provider_type",
            field=models.CharField(default="", max_length=300),
        ),
    ]
