# Generated by Django 5.0.8 on 2024-09-28 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0023_interestedprofessional_most_common_denial_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interestedprofessional",
            name="provider_type",
        ),
    ]
