# Generated by Django 5.0.8 on 2024-09-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0024_remove_interestedprofessional_provider_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="employer_name",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
