# Generated by Django 5.0.8 on 2024-10-02 02:12

from django.db import migrations, models

import fighthealthinsurance.models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0026_denialtypes_diagnosis_regex_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="follow_up_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="denial",
            name="follow_up_sent_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="followup_semi_sekret",
            field=models.CharField(
                default=fighthealthinsurance.models.sekret_gen, max_length=100
            ),
        ),
        migrations.AddField(
            model_name="denial",
            name="more_follow_up_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="denial",
            name="more_follow_up_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="denial",
            name="more_follow_up_sent_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="user_comments",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="user_responsed",
            field=models.BooleanField(default=False),
        ),
    ]
