# Generated by Django 5.0.8 on 2024-10-05 05:26

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0029_denial_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowUpDocs",
            fields=[
                ("document_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "followup_document",
                    models.FileField(
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="external_data"
                        ),
                        upload_to="",
                    ),
                ),
                (
                    "denial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.denial",
                    ),
                ),
            ],
        ),
    ]
