# Generated by Django 5.0.8 on 2024-10-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0030_followupdocs"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FollowUpDocs",
            new_name="FollowUpDocuments",
        ),
        migrations.AddField(
            model_name="denial",
            name="last_interaction",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
