# Generated by Django 5.0.8 on 2024-10-05 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0031_rename_followupdocs_followupdocuments_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="denial",
            old_name="followup_semi_sekret",
            new_name="follow_up_semi_sekret",
        ),
    ]
