# Generated by Django 5.0.8 on 2024-10-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0032_rename_followup_semi_sekret_denial_follow_up_semi_sekret",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="follow_up_medicare_someone_to_help",
            field=models.BooleanField(default=False),
        ),
    ]
