# Generated by Django 5.1.2 on 2024-10-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0033_pubmedarticlesummarized_pubquerymeddata"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="follow_up_medicare_someone_to_help",
            field=models.BooleanField(default=False),
        ),
    ]
