# Generated by Django 5.1.2 on 2024-10-11 22:21

import django.db.models.deletion
import fighthealthinsurance.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0034_alter_followupdocuments_followup_document_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="denial",
            name="follow_up_semi_sekret",
        ),
        migrations.RemoveField(
            model_name="denial",
            name="follow_up_sent",
        ),
        migrations.RemoveField(
            model_name="denial",
            name="follow_up_sent_date",
        ),
        migrations.RemoveField(
            model_name="denial",
            name="more_follow_up_requested",
        ),
        migrations.RemoveField(
            model_name="denial",
            name="more_follow_up_sent",
        ),
        migrations.RemoveField(
            model_name="denial",
            name="more_follow_up_sent_date",
        ),
        migrations.RemoveField(
            model_name="denial",
            name="user_comments",
        ),
        migrations.RemoveField(
            model_name="denial",
            name="user_responsed",
        ),
        migrations.AddField(
            model_name="followupsched",
            name="follow_up_semi_sekret",
            field=models.CharField(
                default=fighthealthinsurance.utils.sekret_gen, max_length=100
            ),
        ),
        migrations.AddField(
            model_name="followupsched",
            name="follow_up_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="followupsched",
            name="follow_up_sent_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                ("followup_id", models.AutoField(primary_key=True, serialize=False)),
                ("more_follow_up_requested", models.BooleanField(default=False)),
                (
                    "follow_up_medicare_someone_to_help",
                    models.BooleanField(default=False),
                ),
                ("user_comments", models.TextField(null=True)),
                (
                    "denial_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.denial",
                    ),
                ),
            ],
        ),
    ]
