# Generated by Django 5.1.2 on 2024-10-12 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0035_remove_denial_follow_up_semi_sekret_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followupsched",
            name="follow_up_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fighthealthinsurance.followuptype",
            ),
        ),
    ]
