# Generated by Django 5.1.2 on 2024-10-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0038_followup_email_followup_name_for_quote_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="followup",
            name="use_quote",
            field=models.BooleanField(default=False),
        ),
    ]
