# Generated by Django 5.1.2 on 2024-10-13 04:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0039_alter_followup_use_quote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denial",
            name="uuid",
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=300),
        ),
    ]
