# Generated by Django 5.1.2 on 2024-10-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0040_alter_denial_uuid"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PubQueryMedData",
            new_name="PubMedQueryData",
        ),
        migrations.AddField(
            model_name="denial",
            name="reference_summary",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="references",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pubmedarticlesummarized",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
