# Generated by Django 5.1.2 on 2024-10-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0042_alter_pubmedarticlesummarized_basic_summary_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FaxesToSend",
            fields=[
                ("fax_id", models.AutoField(primary_key=True, serialize=False)),
                ("hashed_email", models.CharField(max_length=300)),
                ("date", models.DateField(auto_now_add=True)),
                ("paid", models.BooleanField()),
                ("email", models.CharField(max_length=300)),
                ("appeal_text", models.TextField()),
                ("pmids", models.CharField(max_length=300)),
                ("health_history", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="denial",
            name="appeal_fax_number",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
