# Generated by Django 5.1.2 on 2024-11-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0044_faxestosend_combined_document_faxestosend_denial_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="faxestosend",
            name="attempting_to_send_as_of",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="followupsched",
            name="attempting_to_send_as_of",
            field=models.DateField(null=True),
        ),
    ]
