# Generated by Django 5.1.2 on 2024-11-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0045_faxestosend_attempting_to_send_as_of_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faxestosend",
            name="should_send",
            field=models.BooleanField(default=False),
        ),
    ]
