# Generated by Django 5.1.2 on 2024-11-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0046_faxestosend_should_send"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="plan_context",
            field=models.TextField(null=True),
        ),
    ]
