# Generated by Django 5.1.2 on 2024-11-06 22:47

import django.core.files.storage
import fighthealthinsurance.combined_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0049_faxestosend_fax_success"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faxestosend",
            name="combined_document",
            field=models.FileField(
                null=True,
                storage=fighthealthinsurance.combined_storage.CombinedStorage(
                    django.core.files.storage.FileSystemStorage(
                        location="localish_data"
                    ),
                    django.core.files.storage.FileSystemStorage(
                        location="/external_data"
                    ),
                    django.core.files.storage.FileSystemStorage(
                        location="external_data_b"
                    ),
                ),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="followupdocuments",
            name="follow_up_document",
            field=models.FileField(
                null=True,
                storage=fighthealthinsurance.combined_storage.CombinedStorage(
                    django.core.files.storage.FileSystemStorage(
                        location="localish_data"
                    ),
                    django.core.files.storage.FileSystemStorage(
                        location="/external_data"
                    ),
                    django.core.files.storage.FileSystemStorage(
                        location="external_data_b"
                    ),
                ),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="plandocuments",
            name="plan_document",
            field=models.FileField(
                null=True,
                storage=fighthealthinsurance.combined_storage.CombinedStorage(
                    django.core.files.storage.FileSystemStorage(
                        location="localish_data"
                    ),
                    django.core.files.storage.FileSystemStorage(
                        location="/external_data"
                    ),
                    django.core.files.storage.FileSystemStorage(
                        location="external_data_b"
                    ),
                ),
                upload_to="",
            ),
        ),
    ]
