# Generated by Django 5.1.2 on 2024-11-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0050_alter_faxestosend_combined_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faxestosend",
            name="attempting_to_send_as_of",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="faxestosend",
            name="health_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="faxestosend",
            name="pmids",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
