# Generated by Django 5.1.2 on 2024-11-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0051_alter_faxestosend_attempting_to_send_as_of_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="faxestosend",
            name="attempting_to_send_as_of",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
