# Generated by Django 5.1.2 on 2024-11-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0052_alter_faxestosend_attempting_to_send_as_of"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denial",
            name="appeal_fax_number",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
