# Generated by Django 5.1.2 on 2024-11-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0053_alter_denial_appeal_fax_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="your_state",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
