# Generated by Django 5.1.2 on 2024-11-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0054_denial_your_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="pubmedarticlesummarized",
            name="article_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pubmedarticlesummarized",
            name="doi",
            field=models.TextField(blank=True, null=True),
        ),
    ]
