# Generated by Django 5.1.2 on 2024-12-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0055_pubmedarticlesummarized_article_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="extract_procedure_diagnosis_finished",
            field=models.BooleanField(default=False),
        ),
    ]
