# Generated by Django 5.1.2 on 2024-12-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0056_denial_extract_procedure_diagnosis_finished"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denial",
            name="extract_procedure_diagnosis_finished",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
