# Generated by Django 5.1.4 on 2025-01-13 05:39

import django.core.files.storage
import django_encrypted_filefield.fields
import fighthealthinsurance.combined_storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0057_alter_denial_extract_procedure_diagnosis_finished",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="faxestosend",
            name="combined_document_enc",
            field=django_encrypted_filefield.fields.EncryptedFileField(
                null=True,
                storage=fighthealthinsurance.combined_storage.CombinedStorage(
                    django.core.files.storage.FileSystemStorage(
                        location="localish_data"
                    ),
                    django.core.files.storage.FileSystemStorage(
                        location="/external_data"
                    ),
                    django.core.files.storage.FileSystemStorage(
                        location="external_data_b"
                    ),
                ),
                upload_to="",
            ),
        ),
        migrations.AddField(
            model_name="followupdocuments",
            name="follow_up_document_enc",
            field=django_encrypted_filefield.fields.EncryptedFileField(
                null=True,
                storage=fighthealthinsurance.combined_storage.CombinedStorage(
                    django.core.files.storage.FileSystemStorage(
                        location="localish_data"
                    ),
                    django.core.files.storage.FileSystemStorage(
                        location="/external_data"
                    ),
                    django.core.files.storage.FileSystemStorage(
                        location="external_data_b"
                    ),
                ),
                upload_to="",
            ),
        ),
        migrations.AddField(
            model_name="plandocuments",
            name="plan_document_enc",
            field=django_encrypted_filefield.fields.EncryptedFileField(
                null=True,
                storage=fighthealthinsurance.combined_storage.CombinedStorage(
                    django.core.files.storage.FileSystemStorage(
                        location="localish_data"
                    ),
                    django.core.files.storage.FileSystemStorage(
                        location="/external_data"
                    ),
                    django.core.files.storage.FileSystemStorage(
                        location="external_data_b"
                    ),
                ),
                upload_to="",
            ),
        ),
    ]
