# Generated by Django 5.1.4 on 2025-01-26 03:53

import regex_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0058_faxestosend_combined_document_enc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denialtypes",
            name="diagnosis_regex",
            field=regex_field.fields.RegexField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="denialtypes",
            name="form",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="denialtypes",
            name="negative_regex",
            field=regex_field.fields.RegexField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name="denialtypes",
            name="procedure_regex",
            field=regex_field.fields.RegexField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="interestedprofessional",
            name="address",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="interestedprofessional",
            name="business_name",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="interestedprofessional",
            name="comments",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="interestedprofessional",
            name="job_title_or_provider_type",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="interestedprofessional",
            name="most_common_denial",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="interestedprofessional",
            name="name",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="interestedprofessional",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="pubmedarticlesummarized",
            name="publication_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pubmedarticlesummarized",
            name="says_effective",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
