# Generated by Django 5.1.4 on 2025-01-26 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0061_alter_denial_denial_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denial",
            name="appeal_fax_number",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="denial",
            name="appeal_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="denial",
            name="claim_id",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="denial",
            name="plan_context",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="denial",
            name="qa_context",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="denial",
            name="regulator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fighthealthinsurance.regulator",
            ),
        ),
        migrations.AlterField(
            model_name="denial",
            name="state",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
