# Generated by Django 5.1.4 on 2025-01-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0062_alter_denial_appeal_fax_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="professional",
            field=models.BooleanField(default=False),
        ),
    ]
