# Generated by Django 5.1.4 on 2025-02-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0063_denial_user_consumerdomainrelation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="denial",
            name="user",
        ),
    ]
