# Generated by Django 5.1.4 on 2025-02-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0063_denialdomainrelation_denialprofessionalrelation",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="interestedprofessional",
            name="mod_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="interestedprofessional",
            name="signup_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
