# Generated by Django 5.1.4 on 2025-02-05 06:25

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0064_interestedprofessional_mod_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appeal_text", models.TextField(max_length=3000000000, null=True)),
                (
                    "for_denial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.denial",
                    ),
                ),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("Appeal"),
                models.Model,
            ),
        ),
    ]
