# Generated by Django 5.1.4 on 2025-02-03 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0064_remove_denial_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professionaldomainrelation",
            name="domain",
        ),
        migrations.RemoveField(
            model_name="professionaldomainrelation",
            name="professional",
        ),
        migrations.DeleteModel(
            name="ConsumerDomainRelation",
        ),
        migrations.DeleteModel(
            name="ProfessionalDomainRelation",
        ),
    ]
