# Generated by Django 5.1.4 on 2025-02-08 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0065_appeal"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeProduct",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300)),
                ("stripe_id", models.CharField(max_length=300)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="StripePrice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("stripe_id", models.CharField(max_length=300)),
                ("amount", models.IntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.stripeproduct",
                    ),
                ),
            ],
        ),
    ]
