# Generated by Django 5.1.4 on 2025-02-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0066_stripeproduct_stripeprice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="denialdomainrelation",
            name="domain",
        ),
    ]
