# Generated by Django 5.1.4 on 2025-02-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0068_denialdomainrelation_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingListSubscriber",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, default="", max_length=300)),
                ("comments", models.TextField(blank=True, default="")),
                ("signup_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
