# Generated by Django 5.1.4 on 2025-02-11 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0016_alter_professionaldomainrelation_active_and_more"),
        ("fighthealthinsurance", "0069_mailinglistsubscriber"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DenialProfessionalRelation",
            new_name="SecondaryDenialProfessionalRelation",
        ),
        migrations.AddField(
            model_name="appeal",
            name="domain",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fhi_users.userdomain",
            ),
        ),
        migrations.AddField(
            model_name="appeal",
            name="patient_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fhi_users.patientuser",
            ),
        ),
        migrations.AddField(
            model_name="appeal",
            name="primary_professional",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fhi_users.professionaluser",
            ),
        ),
        migrations.AddField(
            model_name="denial",
            name="domain",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fhi_users.userdomain",
            ),
        ),
        migrations.AddField(
            model_name="denial",
            name="patient_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fhi_users.patientuser",
            ),
        ),
        migrations.AddField(
            model_name="denial",
            name="primary_professional",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fhi_users.professionaluser",
            ),
        ),
        migrations.CreateModel(
            name="SecondaryAppealProfessionalRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appeal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.appeal",
                    ),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fhi_users.professionaluser",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DenialDomainRelation",
        ),
    ]
