# Generated by Django 5.1.4 on 2025-02-12 05:53

import django.core.files.storage
import django_encrypted_filefield.fields
import fighthealthinsurance.combined_storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0070_rename_denialprofessionalrelation_secondarydenialprofessionalrelation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="appeal",
            name="document_enc",
            field=django_encrypted_filefield.fields.EncryptedFileField(
                null=True,
                storage=fighthealthinsurance.combined_storage.CombinedStorage(
                    django.core.files.storage.FileSystemStorage(
                        location="localish_data"
                    ),
                    django.core.files.storage.FileSystemStorage(
                        location="/external_data"
                    ),
                    django.core.files.storage.FileSystemStorage(
                        location="external_data_b"
                    ),
                ),
                upload_to="",
            ),
        ),
    ]
