# Generated by Django 5.1.4 on 2025-02-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0071_appeal_document_enc"),
    ]

    operations = [
        migrations.AddField(
            model_name="appeal",
            name="pending",
            field=models.BooleanField(default=True),
        ),
    ]
