# Generated by Django 5.1.4 on 2025-02-12 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0074_appeal_uuid_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appeal",
            old_name="uuid_field",
            new_name="uuid",
        ),
    ]
