# Generated by Django 5.1.4 on 2025-02-12 06:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0075_rename_uuid_field_appeal_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appeal",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
