# Generated by Django 5.1.4 on 2025-02-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0076_alter_appeal_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="appeal",
            name="patient_visible",
            field=models.BooleanField(default=True),
        ),
    ]
