# Generated by Django 5.1.4 on 2025-02-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0076_appeal_patient_visible_denial_patient_visible_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appeal",
            name="combined_document_enc",
        ),
        migrations.AddField(
            model_name="appeal",
            name="hashed_email",
            field=models.CharField(default="fake", max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appeal",
            name="pubmed_ids_json",
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name="denial",
            name="professional_to_finish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="faxestosend",
            name="professional",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="interestedprofessional",
            name="thankyou_email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="faxestosend",
            name="pmids",
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
