# Generated by Django 5.1.4 on 2025-02-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0076_appeal_patient_visible_denial_patient_visible_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="interestedprofessional",
            name="thankyou_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
