# Generated by Django 5.1.4 on 2025-02-18 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fhi_users",
            "0022_professionaluser_domains_userdomain_professionals_and_more",
        ),
        ("fighthealthinsurance", "0077_remove_appeal_combined_document_enc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appeal",
            name="creating_professional",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appeals_created",
                to="fhi_users.professionaluser",
            ),
        ),
        migrations.AddField(
            model_name="denial",
            name="creating_professional",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="denials_created",
                to="fhi_users.professionaluser",
            ),
        ),
        migrations.AlterField(
            model_name="appeal",
            name="primary_professional",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appeals_primary",
                to="fhi_users.professionaluser",
            ),
        ),
        migrations.AlterField(
            model_name="denial",
            name="primary_professional",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="denials_primary",
                to="fhi_users.professionaluser",
            ),
        ),
    ]
