# Generated by Django 5.1.4 on 2025-02-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0077_interestedprofessional_thankyou_email_sent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appeal",
            name="combined_document_enc",
        ),
        migrations.AddField(
            model_name="appeal",
            name="hashed_email",
            field=models.CharField(default="dne", max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appeal",
            name="pubmed_ids_json",
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name="denial",
            name="professional_to_finish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="faxestosend",
            name="professional",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="faxestosend",
            name="pmids",
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
