# Generated by Django 5.1.4 on 2025-02-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0077_appeal_patient_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="patient_visible",
            field=models.BooleanField(default=True),
        ),
    ]
