# Generated by Django 5.1.4 on 2025-02-19 19:37

import django.core.files.storage
import django_encrypted_filefield.fields
import fighthealthinsurance.combined_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0078_appeal_creating_professional_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appeal",
            name="mod_date",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="appeal",
            name="patient_send",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="appeal",
            name="pending_patient",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appeal",
            name="pending_professional",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="appeal",
            name="professional_send",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="appeal",
            name="response_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="appeal",
            name="response_document_enc",
            field=django_encrypted_filefield.fields.EncryptedFileField(
                null=True,
                storage=fighthealthinsurance.combined_storage.CombinedStorage(
                    django.core.files.storage.FileSystemStorage(
                        location="localish_data"
                    ),
                    django.core.files.storage.FileSystemStorage(
                        location="/external_data"
                    ),
                    django.core.files.storage.FileSystemStorage(
                        location="external_data_b"
                    ),
                    None,
                ),
                upload_to="",
            ),
        ),
        migrations.AddField(
            model_name="appeal",
            name="response_text",
            field=models.TextField(max_length=3000000000, null=True),
        ),
        migrations.AddField(
            model_name="appeal",
            name="sent",
            field=models.BooleanField(default=False),
        ),
    ]
