# Generated by Django 5.1.4 on 2025-02-23 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0079_appeal_mod_date_appeal_patient_send_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DenialQA",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.TextField(max_length=3000)),
                ("text_answer", models.TextField(max_length=3000)),
                ("bool_answer", models.BooleanField(default=False)),
                (
                    "denial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.denial",
                    ),
                ),
            ],
        ),
    ]
