# Generated by Django 5.1.4 on 2025-02-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0080_denialqa"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="fax_phone",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
