# Generated by Django 5.1.4 on 2025-02-23 23:56

import django.core.files.storage
import django.db.models.deletion
import django_encrypted_filefield.fields
import fighthealthinsurance.combined_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0081_denial_fax_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="denial",
            name="fax_phone",
        ),
        migrations.CreateModel(
            name="AppealAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    django_encrypted_filefield.fields.EncryptedFileField(
                        null=True,
                        storage=fighthealthinsurance.combined_storage.CombinedStorage(
                            django.core.files.storage.FileSystemStorage(
                                location="localish_data"
                            ),
                            django.core.files.storage.FileSystemStorage(
                                location="/external_data"
                            ),
                            django.core.files.storage.FileSystemStorage(
                                location="external_data_b"
                            ),
                            None,
                        ),
                        upload_to="",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=127)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appeal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="fighthealthinsurance.appeal",
                    ),
                ),
            ],
        ),
    ]
