# Generated by Django 5.1.4 on 2025-02-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0082_remove_denial_fax_phone_appealattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appeal",
            name="creation_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
