# Generated by Django 5.1.5 on 2025-03-05 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0083_appeal_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="appeal",
            name="fax",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fighthealthinsurance.faxestosend",
            ),
        ),
        migrations.AddField(
            model_name="denial",
            name="date_of_service",
            field=models.CharField(default="", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="faxestosend",
            name="for_appeal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fighthealthinsurance.appeal",
            ),
        ),
    ]
