# Generated by Django 5.1.5 on 2025-03-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0084_appeal_fax_faxestosend_for_appeal"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="date_of_service",
            field=models.CharField(default="", max_length=300, null=True),
        ),
    ]
