# Generated by Django 5.1.5 on 2025-03-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0085_appeal_success"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="health_history_anonymized",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="provider_in_network",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="single_case",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
