# Generated by Django 5.1.5 on 2025-03-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0085_denial_date_of_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denial",
            name="date_of_service",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
