# Generated by Django 5.1.4 on 2025-02-03 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalUserRelation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "child_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_child_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_parent_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
