# Generated by Django 5.1.4 on 2025-02-05 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="professionaldomainrelation",
            name="display_name",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="professionaldomainrelation",
            name="professional_type",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="professionaluser",
            name="most_common_denial",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="userdomain",
            name="address1",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="userdomain",
            name="address2",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="userdomain",
            name="city",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="userdomain",
            name="country",
            field=models.CharField(default="USA", max_length=150),
        ),
        migrations.AddField(
            model_name="userdomain",
            name="display_name",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="userdomain",
            name="internal_phone_number",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="userdomain",
            name="office_fax",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="userdomain",
            name="state",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userdomain",
            name="visible_phone_number",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="userdomain",
            name="zipcode",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.RenameModel(
            old_name="ConsumerUser",
            new_name="PatientUser",
        ),
        migrations.CreateModel(
            name="PatientDomainRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField()),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fhi_users.userdomain",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fhi_users.patientuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserContactInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("phone_number", models.CharField(max_length=150, null=True)),
                ("country", models.CharField(default="USA", max_length=150)),
                ("state", models.CharField(max_length=50, null=True)),
                ("city", models.CharField(max_length=150, null=True)),
                ("address1", models.CharField(max_length=200, null=True)),
                ("address2", models.CharField(max_length=200, null=True)),
                ("zipcode", models.CharField(max_length=20, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ConsumerDomainRelation",
        ),
    ]
