# Generated by Django 5.1.4 on 2025-02-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdomain",
            name="name",
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
