# Generated by Django 5.1.4 on 2025-02-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0002_professionaldomainrelation_display_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionaldomainrelation",
            name="pending",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="patientdomainrelation",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
