# Generated by Django 5.1.4 on 2025-02-09 18:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("fhi_users", "0005_alter_userdomain_address1_alter_userdomain_city_and_more"),
        ("fhi_users", "0006_alter_userdomain_visible_phone_number"),
        (
            "fhi_users",
            "0007_remove_professionaldomainrelation_approval_required_and_more",
        ),
        ("fhi_users", "0008_professionaluser_provider_type"),
        ("fhi_users", "0009_userdomain_uuid"),
        ("fhi_users", "0010_remove_patientdomainrelation_domain_and_more"),
        ("fhi_users", "0011_remove_userdomain_id_userdomain_uuid"),
        ("fhi_users", "0012_patientdomainrelation_domain_and_more"),
        ("fhi_users", "0013_rename_uuid_userdomain_id"),
        ("fhi_users", "0014_userextraproperties"),
        ("fhi_users", "0015_rename_userextraproperties_extrauserproperties_and_more"),
    ]

    dependencies = [
        ("fhi_users", "0004_remove_patientdomainrelation_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdomain",
            name="address1",
            field=models.CharField(default="oops", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="city",
            field=models.CharField(default="nowhere", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="display_name",
            field=models.CharField(default="FakePlace", max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="internal_phone_number",
            field=models.CharField(default="12345566,,9", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="state",
            field=models.CharField(default="BEST", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="zipcode",
            field=models.CharField(default="94112-72", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="visible_phone_number",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.RemoveField(
            model_name="professionaldomainrelation",
            name="approval_required",
        ),
        migrations.AddField(
            model_name="professionaldomainrelation",
            name="rejected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="professionaldomainrelation",
            name="suspended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="professionaluser",
            name="provider_type",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.RemoveField(
            model_name="patientdomainrelation",
            name="domain",
        ),
        migrations.RemoveField(
            model_name="professionaldomainrelation",
            name="domain",
        ),
        migrations.RemoveField(
            model_name="userdomain",
            name="id",
        ),
        migrations.AddField(
            model_name="userdomain",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=300,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="patientdomainrelation",
            name="domain",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="fhi_users.userdomain",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professionaldomainrelation",
            name="domain",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="fhi_users.userdomain",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ExtraUserProperties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
