# Generated by Django 5.1.4 on 2025-02-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0004_remove_patientdomainrelation_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdomain",
            name="address1",
            field=models.CharField(default="oops", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="city",
            field=models.CharField(default="nowhere", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="display_name",
            field=models.CharField(default="FakePlace", max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="internal_phone_number",
            field=models.CharField(default="12345566,,9", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="state",
            field=models.CharField(default="BEST", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="zipcode",
            field=models.CharField(default="94112-72", max_length=20),
            preserve_default=False,
        ),
    ]
