# Generated by Django 5.1.4 on 2025-02-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0005_alter_userdomain_address1_alter_userdomain_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdomain",
            name="visible_phone_number",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
