# Generated by Django 5.1.4 on 2025-02-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0006_alter_userdomain_visible_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professionaldomainrelation",
            name="approval_required",
        ),
        migrations.AddField(
            model_name="professionaldomainrelation",
            name="rejected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="professionaldomainrelation",
            name="suspended",
            field=models.BooleanField(default=False),
        ),
    ]
