# Generated by Django 5.1.4 on 2025-02-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fhi_users",
            "0007_remove_professionaldomainrelation_approval_required_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="professionaluser",
            name="provider_type",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
