# Generated by Django 5.1.4 on 2025-02-08 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0008_professionaluser_provider_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdomain",
            name="uuid",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=300, unique=True
            ),
        ),
    ]
