# Generated by Django 5.1.4 on 2025-02-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0009_userdomain_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientdomainrelation",
            name="domain",
        ),
        migrations.RemoveField(
            model_name="professionaldomainrelation",
            name="domain",
        ),
        migrations.RemoveField(
            model_name="userdomain",
            name="uuid",
        ),
    ]
