# Generated by Django 5.1.4 on 2025-02-08 06:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0010_remove_patientdomainrelation_domain_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdomain",
            name="id",
        ),
        migrations.AddField(
            model_name="userdomain",
            name="uuid",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=300,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
