# Generated by Django 5.1.4 on 2025-02-08 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0011_remove_userdomain_id_userdomain_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdomainrelation",
            name="domain",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="fhi_users.userdomain",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professionaldomainrelation",
            name="domain",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="fhi_users.userdomain",
            ),
            preserve_default=False,
        ),
    ]
