# Generated by Django 5.1.4 on 2025-02-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0012_patientdomainrelation_domain_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdomain",
            old_name="uuid",
            new_name="id",
        ),
    ]
