# Generated by Django 5.1.4 on 2025-02-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0016_alter_professionaldomainrelation_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientuser",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
