# Generated by Django 5.1.4 on 2025-02-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0017_alter_patientuser_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdomain",
            name="professional_user",
            field=models.ManyToManyField(
                through="fhi_users.ProfessionalDomainRelation",
                to="fhi_users.professionaluser",
            ),
        ),
    ]
