# Generated by Django 5.1.4 on 2025-02-13 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0018_userdomain_professional_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdomain",
            name="professional_user",
        ),
    ]
