# Generated by Django 5.1.4 on 2025-02-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0019_remove_userdomain_professional_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionaluser",
            name="fax_number",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="userdomain",
            name="cover_template_string",
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
