# Generated by Django 5.1.4 on 2025-02-18 01:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0021_resettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionaluser",
            name="domains",
            field=models.ManyToManyField(
                through="fhi_users.ProfessionalDomainRelation",
                to="fhi_users.userdomain",
            ),
        ),
        migrations.AddField(
            model_name="userdomain",
            name="professionals",
            field=models.ManyToManyField(
                through="fhi_users.ProfessionalDomainRelation",
                to="fhi_users.professionaluser",
            ),
        ),
        migrations.AlterField(
            model_name="resettoken",
            name="token",
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
