# Generated by Django 5.1.4 on 2025-02-18 22:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fhi_users",
            "0022_professionaluser_domains_userdomain_professionals_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationtoken",
            name="token",
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
