# Generated by Django 5.1.6 on 2025-02-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0023_alter_verificationtoken_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationtoken",
            name="token",
            field=models.CharField(max_length=255),
        ),
    ]
