# Generated by Django 5.1.4 on 2025-02-19 17:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0024_alter_verificationtoken_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professionaldomainrelation",
            name="display_name",
        ),
        migrations.AddField(
            model_name="patientuser",
            name="display_name",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="professionaluser",
            name="display_name",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="verificationtoken",
            name="token",
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
