# Generated by Django 5.1.4 on 2025-02-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0025_remove_professionaldomainrelation_display_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdomain",
            name="internal_phone_number",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
