# Generated by Django 5.1.4 on 2025-02-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0027_userdomain_business_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdomain",
            name="internal_phone_number",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
