# Generated by Django 5.1.5 on 2025-02-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0028_alter_userdomain_internal_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdomain",
            name="business_name",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
