# Generated by Django 5.1.5 on 2025-03-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0029_alter_userdomain_business_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdomain",
            name="name",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="office_fax",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
