# Generated by Django 5.1.6 on 2025-02-27 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0029_alter_userdomain_business_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdomain",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("80e53e61-fad0-486e-8898-8717a84a95bd"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
