# Generated by Django 5.1.5 on 2025-03-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0030_alter_userdomain_name_alter_userdomain_office_fax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdomain",
            name="address2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
