# Generated by Django 5.1.6 on 2025-03-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0031_alter_userdomain_address2_alter_userdomain_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdomain",
            name="name",
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
