# Generated by Django 5.1.6 on 2025-03-07 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0032_alter_userdomain_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercontactinfo",
            name="phone_number",
            field=models.CharField(
                max_length=150,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number.", regex="^\\+?1?\\d{9,15}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="internal_phone_number",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number.", regex="^\\+?1?\\d{9,15}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="visible_phone_number",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number.", regex="^\\+?1?\\d{9,15}$"
                    )
                ],
            ),
        ),
    ]
